"""nulluble birthdate

Revision ID: 03582aa6425d
Revises: 927de6becd43
Create Date: 2024-10-17 20:43:11.391496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03582aa6425d'
down_revision: Union[str, None] = '927de6becd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthdate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthdate',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
