"""add_isbn_field_to_borrow_model

Revision ID: e9dc4d50f463
Revises: 5127547cc9f7
Create Date: 2024-10-18 08:33:26.383053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9dc4d50f463'
down_revision: Union[str, None] = '5127547cc9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_history', sa.Column('book_isbn', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_history', 'book_isbn')
    # ### end Alembic commands ###
